version: "3"

services:
  database:
    image: postgres
    container_name: barber
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: barber
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
